### ISSUE TITLE
讨论区

### ISSUE THREAD

**Issue by zhu-ty** [zhu-ty/DA32ProtocolCpp#1]
童鞋们好~组内项目启动后我会不定期看看大家的代码并帮助大家修改，这个地方可以作为一个很不错的留言讨论区！
（这也是我第一次试验此功能2333）

**Comment by zhu-ty** [comment]
麻烦看到此消息的在这下边回复下吧~ 我故意不在群内说看看谁能看到~

**Comment by WanLinli1995** [comment]
收到~

## 

祝好

万琳莉 
Wan Linli  (Cicy)
清华大学自动化系
Department of Automation,Tsinghua University
Beijing, 100084, P.R.China
Email: wan-ll13@mails.tsinghua.edu.com
Mobile: 15201301695

在 2015-11-21 00:11:16，"Sherlock Adrian Owen" notifications@github.com 写道：

麻烦看到此消息的在这下边回复下吧~ 我故意不在群内说看看谁能看到~

**Comment by Cwx13** [comment]
居然不能直接回复邮件修改？
